### ISSUE TITLE
Using toSignal in a root-provided service can lead to memory leaks?

### ISSUE THREAD

**Issue by lzonjic** [DeborahK/angular-rxjs-signals-fundamentals#17]
According to @NetanelBasal  `toSignal` uses the injector’s context for unsubscription by default. When used in a root service, this can lead to memory leaks when the consuming component is destroyed. More on that you can read here: https://netbasal.com/navigating-the-nuances-of-tosignal-in-angular-what-to-know-e4d6a4b5dfaf

Your code, for example the ProductService root service, also uses this potentially dangerous pattern:
```ts
// apm-final/src/app/products/product.service.ts
@Injectable({
  providedIn: 'root'
})
export class ProductService {
  private productsResult = toSignal(this.productsResult$,
    { initialValue: ({ data: [] } as Result<Product[]>) });

  products = computed(() => this.productsResult().data);
  productsError = computed(() => this.productsResult().error);
}
```

```ts
// apm-final/src/app/products/product-list/product-list.component.ts
export class ProductListComponent {
  private productService = inject(ProductService);

  // Products
  products = this.productService.products;
}
```

**Comment by DeborahK** [comment]
In this example, there is no "consuming component". The `toSignal()` is private to the service. So it will remain (on purpose) for the life of the application. And will be destroyed when the application is terminated.

Next time I update this course, I'll be sure to clarify this point.

Thanks!
